/**
 * The C# provider.
 *
 * Two kinds of test. The first is that the output is what a C# developer would have written — the type
 * mapping, the shapes, the layouts. The second is that it refuses rather than weakens, which is the one
 * promise a provider makes that matters more than its taste.
 */

import { describe, expect, it } from "vitest";
import { buildWorkspace, type Decl, type LinkedModel } from "@sevenk/core";
import { buildNames, compileRules, hydrate, inputOf, type Request } from "@sevenk/generate";
import { csharp } from "../src/index.js";

const SOURCE = `
package shop.common

enum Currency {
  Sek
  Eur
}

value Sku : string { length 1..24 }

record Money {
  amount:   decimal(18,2) { range 0.. }
  currency: Currency
}

envelope Trace {
  correlationId: uuid @role(correlation)
  causationId:   uuid @derive(inbound.id) @role(causation)
}
`;

const ORDERS = `
package shop.orders

import shop.common

message PlaceOrder v1.0 @command {
  orderRef:  uuid @role(businessKey)
  sku:       common.Sku
  total:     common.Money
  placedAt:  instant
  quantity:  int
  gift:      bool
  note:      string? { length 1..200 }
}
`;

/** The same two files the model is built from, as a provider would be sent them. */
const SOURCES = [
  { path: "common.7k", source: SOURCE },
  { path: "orders.7k", source: ORDERS },
];

const model = (extra = ""): LinkedModel =>
  buildWorkspace([
    { path: "common.7k", source: SOURCE + extra },
    { path: "orders.7k", source: ORDERS },
  ]).model;

function request(
  m: LinkedModel,
  options: Record<string, unknown> = {},
  layout: Request["layout"] = "per-declaration",
  rules: { where: string; [k: string]: unknown }[] = [],
  only?: (d: Decl) => boolean,
): Request {
  const { names } = buildNames(m, []);
  const compiled = compileRules(m, rules);
  const defaults = { namespace: "Acme", ...options };
  return {
    model: m,
    selected: m.decls.filter((d) => only?.(d) ?? true),
    names,
    layout,
    options: defaults,
    optionsFor: (decl) => compiled.resolve(decl, defaults).options,
  };
}

const generate = (...args: Parameters<typeof request>) => csharp.generate(request(...args));

const fileNamed = (out: ReturnType<typeof generate>, path: string): string =>
  out.artifacts.find((a) => a.path === path)?.content ?? "";

describe("the type mapping", () => {
  const out = () => generate(model());

  it("writes a message as a record, with the kernel types C# actually has", () => {
    const text = fileNamed(out(), "Acme/Shop/Orders/PlaceOrder.cs");
    expect(text).toContain("public sealed partial record PlaceOrder");
    expect(text).toContain("public required Guid OrderRef { get; init; }");
    expect(text).toContain("public required DateTimeOffset PlacedAt { get; init; }");
    expect(text).toContain("public required bool Gift { get; init; }");
  });

  it("maps 7K's `int` to `long`, because 7K's int is 64-bit", () => {
    // The name is the trap: a C# `int` is 32 bits and would silently truncate.
    expect(fileNamed(out(), "Acme/Shop/Orders/PlaceOrder.cs")).toContain(
      "public required long Quantity { get; init; }",
    );
  });

  it("makes an optional field nullable, and not `required`", () => {
    // `required` on something the model says may be absent would be a contradiction.
    const text = fileNamed(out(), "Acme/Shop/Orders/PlaceOrder.cs");
    expect(text).toContain("public string? Note { get; init; }");
    expect(text).not.toContain("required string? Note");
  });

  it("qualifies a type from another package and leaves its own alone", () => {
    const text = fileNamed(out(), "Acme/Shop/Orders/PlaceOrder.cs");
    expect(text).toContain("Acme.Shop.Common.Sku Sku");
    expect(fileNamed(out(), "Acme/Shop/Common/Money.cs")).toContain("public required Currency Currency");
  });

  it("writes an enum and a value", () => {
    expect(fileNamed(out(), "Acme/Shop/Common/Currency.cs")).toContain("public enum Currency");
    const sku = fileNamed(out(), "Acme/Shop/Common/Sku.cs");
    // A nominal value stays nominal: one field, compared by value, and no implicit conversion *in* —
    // passing a bare string where a Sku is meant is the mistake the wrapper exists to prevent.
    expect(sku).toContain("public readonly partial record struct Sku(string Value)");
    expect(sku).toContain("public static implicit operator string(Sku it) => it.Value;");
    expect(sku).not.toContain("implicit operator Sku(string");
  });

  it("marks every file as owned by the generator", () => {
    expect(fileNamed(out(), "Acme/Shop/Common/Currency.cs")).toContain("<auto-generated>");
    expect(fileNamed(out(), "Acme/Shop/Common/Currency.cs")).toContain("Do not edit");
  });
});

describe("the choices it leaves open", () => {
  it("writes a message as a class when asked", () => {
    const text = fileNamed(generate(model(), { messageType: "class" }), "Acme/Shop/Orders/PlaceOrder.cs");
    expect(text).toContain("public sealed partial class PlaceOrder");
  });

  it("lets one declaration differ from the rest", () => {
    // The point of per-declaration options: the whole model one way, one awkward message another.
    const out = generate(model(), {}, "per-declaration", [
      { where: "message:shop.orders.PlaceOrder", messageType: "class" },
    ]);
    expect(fileNamed(out, "Acme/Shop/Orders/PlaceOrder.cs")).toContain("sealed partial class PlaceOrder");
    expect(fileNamed(out, "Acme/Shop/Common/Money.cs")).toContain("sealed partial record Money");
  });

  it("collapses a value to the type it refines when asked, and writes no wrapper for it", () => {
    const out = generate(model(), { valueTypes: "alias" });
    expect(out.artifacts.map((a) => a.path)).not.toContain("Acme/Shop/Common/Sku.cs");
    expect(fileNamed(out, "Acme/Shop/Orders/PlaceOrder.cs")).toContain("public required string Sku");
  });

  it("can drop `#nullable enable`", () => {
    expect(fileNamed(generate(model(), { nullable: false }), "Acme/Shop/Common/Money.cs")).not.toContain(
      "#nullable",
    );
  });
});

describe("layouts", () => {
  it("writes one file per package", () => {
    const out = generate(model(), {}, "per-package");
    expect(out.artifacts.map((a) => a.path).sort()).toEqual([
      "Acme.Shop.Common.cs",
      "Acme.Shop.Orders.cs",
      // The shared support, which belongs to no package and so is not one of their files.
      "Acme/Json.cs",
      "Acme/Validation.cs",
    ]);
    expect(fileNamed(out, "Acme.Shop.Common.cs")).toContain("namespace Acme.Shop.Common;");
  });

  it("writes one file for everything, with block-scoped namespaces", () => {
    const out = generate(model(), {}, "single");
    expect(out.artifacts).toHaveLength(1);
    const text = out.artifacts[0]!.content;
    // A file-scoped namespace cannot be followed by another, so a single file has to use blocks.
    expect(text).toContain("namespace Acme.Shop.Common\n{");
    expect(text).toContain("namespace Acme.Shop.Orders\n{");
    expect(text).not.toContain("namespace Acme.Shop.Common;");
  });

  it("offers exactly the layouts it can actually produce", () => {
    expect(csharp.layouts).toEqual(["per-declaration", "per-package", "single"]);
  });
});

describe("what it refuses", () => {
  it("refuses a decimal wider than C# can hold, rather than widening it to a double", () => {
    // 7K allows `decimal(p,s)` to p=38; C#'s decimal holds 28-29 significant digits. A `double` here
    // would be a rounding bug on money with a specification behind it.
    const out = generate(model("\nrecord Big {\n  amount: decimal(38,4)\n}\n"));
    expect(out.refusals).toHaveLength(1);
    const refusal = out.refusals[0]!;
    expect(refusal.at).toBe("shop.common.Big");
    expect(refusal.declared).toBe("decimal(38,4)");
    expect(refusal.because).toContain("28 significant digits");
  });

  it("carries the gap in the draft file, not only in the report", () => {
    // What makes a forgiving run safe: the artifact announces its own defect, so partial output cannot
    // be mistaken for finished output.
    const out = generate(model("\nrecord Big {\n  amount: decimal(38,4)\n}\n"));
    const draft = out.refusals[0]!.draft ?? [];
    expect(draft).toHaveLength(1);
    expect(draft[0]!.content).toContain("#error 7K:");
    expect(draft[0]!.content).toContain("decimal(38,4)");
  });

  it("writes nothing for the declaration it refused", () => {
    const out = generate(model("\nrecord Big {\n  amount: decimal(38,4)\n}\n"));
    expect(out.artifacts.map((a) => a.path)).not.toContain("Acme/Shop/Common/Big.cs");
    // And everything else still came out, so one bad declaration does not hide the rest.
    expect(out.artifacts.length).toBeGreaterThan(3);
  });

  it("refuses an `at` that names the declaration, so a tool can point at it", () => {
    // Spider highlights the node a refusal is about; that only works if `at` is a qualified name.
    const m = model("\nrecord Big {\n  amount: decimal(38,4)\n}\n");
    const out = csharp.generate(request(m));
    expect(m.decls.some((d) => `${d.id.pkg}.${d.id.name}` === out.refusals[0]!.at)).toBe(true);
  });
});

describe("determinism", () => {
  it("gives byte-identical output for the same input", () => {
    // Generated code that diffs noisily is generated code nobody reviews.
    const a = generate(model());
    const b = generate(model());
    expect(a.artifacts.map((x) => `${x.path}\n${x.content}`)).toEqual(
      b.artifacts.map((x) => `${x.path}\n${x.content}`),
    );
  });

  it("does not depend on what else was selected", () => {
    const whole = generate(model());
    const part = generate(model(), {}, "per-declaration", [], (d) => d.id.name === "PlaceOrder");
    expect(fileNamed(part, "Acme/Shop/Orders/PlaceOrder.cs")).toBe(
      fileNamed(whole, "Acme/Shop/Orders/PlaceOrder.cs"),
    );
  });
});

describe("provenance", () => {
  it("says which declaration each file came from", () => {
    // A path is a convention; this is a fact. It is what lets a tool point at the model rather than
    // guess from a filename.
    const out = generate(model());
    const placed = out.artifacts.find((a) => a.path.endsWith("PlaceOrder.cs"));
    expect(placed?.from).toEqual(["shop.orders.PlaceOrder"]);
  });

  it("names every declaration in a file that holds several", () => {
    const out = generate(model(), {}, "per-package");
    const common = out.artifacts.find((a) => a.path === "Acme.Shop.Common.cs");
    expect(common?.from).toContain("shop.common.Money");
    expect(common?.from).toContain("shop.common.Currency");
    expect(common?.from?.length).toBeGreaterThan(2);
  });

  it("names them all for a single file", () => {
    // One file for everything, so its provenance is everything the per-declaration run wrote a file
    // for — the support file aside, which comes from no declaration and says so with an empty `from`.
    const single = generate(model(), {}, "single");
    const each = generate(model()).artifacts.filter((a) => a.from.length > 0);
    expect(single.artifacts[0]?.from?.length).toBe(each.length);
    expect(single.artifacts[0]?.from).toContain("shop.orders.PlaceOrder");
  });

  it("carries it on a draft too, so a refusal points somewhere", () => {
    const out = generate(model("\nrecord Big {\n  amount: decimal(38,4)\n}\n"));
    expect(out.refusals[0]?.draft?.[0]?.from).toEqual(["shop.common.Big"]);
  });
});

describe("across a process boundary", () => {
  it("generates byte-identical C# from a request that went through JSON", () => {
    // The claim that matters for ever running this provider out of process: the far side sees the same
    // model, resolves the same cross-package references, and emits the same bytes. If this fails, moving
    // a provider changes somebody's generated code, which is the worst way to find out.
    const m = model();
    const here = csharp.generate(request(m));
    const there = csharp.generate(
      hydrate(JSON.parse(JSON.stringify(inputOf(request(m), SOURCES)))),
    );

    expect(there.artifacts.map((a) => `${a.path}\n${a.content}`)).toEqual(
      here.artifacts.map((a) => `${a.path}\n${a.content}`),
    );
    // And the cross-package reference really was resolved on the far side, rather than degraded.
    expect(there.artifacts.find((a) => a.path.endsWith("PlaceOrder.cs"))?.content).toContain(
      "Acme.Shop.Common.Money Total",
    );
  });

  it("keeps a per-declaration option across the boundary", () => {
    const m = model();
    const rules = [{ where: "message:shop.orders.PlaceOrder", messageType: "class" }];
    const there = csharp.generate(
      hydrate(JSON.parse(JSON.stringify(inputOf(request(m, {}, "per-declaration", rules), SOURCES)))),
    );
    expect(
      there.artifacts.find((a) => a.path.endsWith("PlaceOrder.cs"))?.content,
    ).toContain("sealed partial class PlaceOrder");
  });
});
