// Runs the generated validators over the same payloads 7K Core's contract runtime is run over.
//
// `scripts/validation.mjs` runs both and compares. This side owns the one thing the other cannot do for
// it: handing a body to the validator this provider generated, and writing down what it said.
//
// **The body is deserialised rather than built by hand**, which is the opposite of what `Equivalence.cs`
// does, and for a reason. That file warns that reflecting JSON into records with required properties and
// nominal wrappers needs a converter per wrapper, and that a bug in one would look exactly like a
// disagreement about the saga. The same risk is here — but the converters are generated by this provider
// and round-tripping them is already asserted in `Behaviour.cs`, so they are a tested path rather than
// an unknown one. And where it does go wrong, this says so in its own words (`!!`) instead of reporting
// an empty problem list, so the harness can tell "could not read it" from "found nothing wrong with it".
// Hand-writing a factory per payload would have meant keeping two descriptions of every case in step,
// which is its own way of producing a difference that means nothing.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Acme;
using Acme.Verify.Orders;

static class Validation
{
    static int Main()
    {
        // Beside the executable's project, where `validation.mjs` copies them.
        const string dir = "payloads";

        foreach (var path in Directory.GetFiles(dir, "*.json").OrderBy(p => p, StringComparer.Ordinal))
        {
            Console.WriteLine("## " + Path.GetFileNameWithoutExtension(path));

            var file = JsonNode.Parse(File.ReadAllText(path))!.AsObject();
            var type = (string)file["type"]!;
            var body = file["body"]!;

            IReadOnlyList<Problem> problems;
            try
            {
                problems = Check(type, body);
            }
            catch (Exception failure)
            {
                // Said rather than swallowed: an unreadable body is a different fact from a body with
                // nothing wrong with it, and a harness that could not tell them apart would report a
                // converter bug as agreement.
                Console.WriteLine($"!! {failure.GetType().Name}: {Oneline(failure.Message)}");
                continue;
            }

            // Sorted, because the order a validator finds things in is not part of the contract and
            // comparing it would be comparing two tree walks.
            foreach (var problem in problems.OrderBy(p => p.ToString(), StringComparer.Ordinal))
                Console.WriteLine($"{problem.Path} | {problem.Rule}");
        }

        return 0;
    }

    /// Dispatches by the model's own name for the message, which is what the payload file carries.
    static IReadOnlyList<Problem> Check(string type, JsonNode body) => type switch
    {
        "verify.orders.PlaceOrder" => PlaceOrderValidator.Validate(Read<PlaceOrder>(body)),
        "verify.orders.Everything" => EverythingValidator.Validate(Read<Everything>(body)),
        _ => throw new InvalidOperationException($"no validator is wired up for `{type}`"),
    };

    static T Read<T>(JsonNode body) =>
        body.Deserialize<T>(SevenKJson.Options)
        ?? throw new InvalidOperationException("the body read as null");

    static string Oneline(string text) => text.Replace("\r", " ").Replace("\n", " ");
}
